import pytest

from ohqbuilder.model.outlet import Outlet
from ohqbuilder.model.reach import Reach
from ohqbuilder.model.watershed import Watershed
from ohqbuilder.model.subbasin import Subbasin
from ohqbuilder.model.topology import TopologyLink
from ohqbuilder.writers.ohq_writer import OHQWriter
from ohqbuilder.writers.rainfall_writer import rainfall_lines
from ohqbuilder.writers.et_writer import et_lines


def test_writer_renders_subbasin():
    ws = Watershed(
        name="Test",
        subbasins=[
            Subbasin(
                id=1,
                name="Subbasin_1",
                area_km2=1.0,
                curve_number=75,
                downstream="Outlet",
                centroid_x=100.0,
                centroid_y=200.0,
            )
        ],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[TopologyLink(1, "subbasin", "Subbasin_1", "sink", None, "Outlet")],
    )
    txt = OHQWriter().render(ws)
    # CN_Catchment is a composite type: it must be created with "create
    # composite" (which instantiates its internal Retention/R1-R5 cascade),
    # not "create block" (which would leave it an empty, non-functional shell).
    assert "create composite;type=CN_Catchment,name=Subbasin_1" in txt
    assert "CN=75" in txt
    assert "create block;type=fixed_head,name=Outlet" in txt


def test_writer_can_omit_comments():
    ws = Watershed(name="NoComments", outlet=Outlet(x_act=0.0, y_act=0.0))

    txt = OHQWriter(include_comments=False).render(ws)

    assert "# Generated by GIStoOHQ" not in txt
    assert "quantity=alloutputfile, value=NoComments_OHQ_output.txt" in txt
    assert "create block;type=fixed_head,name=Outlet" in txt


def test_simulation_window_rejects_reversed_or_invalid_times(monkeypatch):
    ws = Watershed(name="BadWindow", outlet=Outlet(x_act=0.0, y_act=0.0))

    monkeypatch.setenv("OHQ_SIM_START_TIME", "5")
    monkeypatch.setenv("OHQ_SIM_END_TIME", "5")
    with pytest.raises(ValueError, match="greater than"):
        OHQWriter().render(ws)

    monkeypatch.setenv("OHQ_SIM_START_TIME", "5")
    monkeypatch.setenv("OHQ_SIM_END_TIME", "1")
    with pytest.raises(ValueError, match="greater than"):
        OHQWriter().render(ws)

    monkeypatch.setenv("OHQ_SIM_START_TIME", "not-a-number")
    monkeypatch.setenv("OHQ_SIM_END_TIME", "1")
    with pytest.raises(ValueError, match="must be numbers"):
        OHQWriter().render(ws)

    monkeypatch.setenv("OHQ_SIM_START_TIME", "0")
    monkeypatch.setenv("OHQ_SIM_END_TIME", "inf")
    with pytest.raises(ValueError, match="must be finite"):
        OHQWriter().render(ws)


def test_rainfall_source_does_not_reference_an_invented_file(monkeypatch):
    monkeypatch.delenv("OHQ_RAINFALL_FILE", raising=False)

    assert rainfall_lines(Watershed(name="NoRainfallFile")) == [
        "create source;type=Precipitation,name=Rain"
    ]


def test_rainfall_source_uses_explicitly_configured_file(monkeypatch):
    monkeypatch.setenv("OHQ_RAINFALL_FILE", "/data/valid_rainfall.txt")

    assert rainfall_lines(Watershed(name="Configured")) == [
        "create source;type=Precipitation,name=Rain,"
        "timeseries=/data/valid_rainfall.txt"
    ]


def test_writer_renders_mixed_hru_with_area_fraction_and_three_outflows():
    ws = Watershed(
        name="Mixed",
        subbasins=[
            Subbasin(
                id=1,
                name="Subbasin_1",
                area_km2=1.0,
                impervious_fraction=0.27,
                flow_len_ft=2000.0,
                surface_elevation_m=84.2,
                centroid_x=100.0,
                centroid_y=200.0,
            )
        ],
        reaches=[Reach(id=1, name="Reach_1", x_act=200.0, y_act=200.0)],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter(formulation="mixed_hru").render(ws)

    assert "mixed_hydrologic_response_unit.json" in text
    assert "mixed_hydrologic_response_unit_final_v2.json" not in text
    # Composite types must use "create composite" - only that command path
    # instantiates a composite's internal members (Soil_1-3, Groundwater,
    # Impervious_Catchment, ...) and propagates its applyto-derived formulas.
    # "create block" builds an empty shell with no internal members at all.
    assert "create composite;type=Mixed_Hydrologic_Response_Unit,name=Subbasin_1" in text
    assert "create block;type=Mixed_Hydrologic_Response_Unit" not in text
    assert "impervious_fraction=0.27" in text
    assert "impervious_reach_length=609.6[m]" in text
    assert "surface_elevation=84.2[m]" in text
    assert "Runoff_coeff=" not in text
    # Mixed_Hydrologic_Response_Unit's Reach/Impervious_Reach members can only
    # be resolved as external exits through their own distinct connector
    # types (Reach_link/Impervious_Reach_link); a composite can resolve just
    # one exit per link "type" string, so both cannot share the underlying
    # Trapezoidal_Channel_link type. Confirmed by actually solving a
    # generated .ohq through OpenHydroQual-Console: using
    # Trapezoidal_Channel_link here fails with "cannot start at composite".
    assert "from=Subbasin_1,to=Reach_1,type=Reach_link" in text
    assert "from=Subbasin_1,to=Reach_1,type=Impervious_Reach_link" in text
    assert "type=Trapezoidal_Channel_link" not in text
    assert "from=Subbasin_1,to=Reach_1,type=groundwater_to_stream" in text
    # groundwater_to_stream's length/area have no template default and a
    # strict >0 criteria (see groundwater.json); an unparameterized link
    # fails model verification before solving, confirmed by actually running
    # a generated .ohq through OpenHydroQual-Console.
    #
    # Flow-path length is now sized from relief/TARGET_GRADIENT (2%), not a
    # bare constant (see ohq_writer.py's Groundwater-fixes commit). This
    # fixture's Reach_1 has no elevation set, and reach_bottom_elevation()
    # falls back to 0 for that - a real, currently-unaddressed gap (missing
    # elevation data reads as "reach is at sea level", not "unknown"), which
    # here manufactures relief = |84.2 - 0| = 84.2m and thus length =
    # 84.2/0.02 = 4210m for this small, low-relief-in-reality test subbasin.
    # This assertion tracks that actual (if imperfect) behavior; it is not an
    # endorsement of treating missing elevation as 0.
    assert "type=groundwater_to_stream,name=Subbasin_1 to Reach_1 baseflow,length=4210[m]" in text
    # No SSURGO texture data on this Subbasin: soil parameters must be
    # omitted so mixed_hydrologic_response_unit.json's generic template
    # defaults apply, not silently written as some fabricated value.
    assert "K_sat=" not in text
    assert "alpha_vG=" not in text
    assert "n_vG=" not in text
    assert "theta_sat=" not in text
    assert "theta_res=" not in text


def test_mixed_hru_impervious_reach_length_falls_back_to_basin_dimension():
    ws = Watershed(
        name="MixedFallback",
        subbasins=[Subbasin(id=1, name="Subbasin_1", area_km2=1.0,
                            centroid_x=100.0, centroid_y=200.0)],
        reaches=[Reach(id=1, name="Reach_1", x_act=200.0, y_act=200.0)],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter(formulation="mixed_hru").render(ws)

    assert "impervious_reach_length=1000[m]" in text


@pytest.mark.parametrize("formulation", ["mixed_hru", "standard_hru"])
def test_linear_reservoir_baseflow_replaces_darcy_without_duplicate_outlet(
    monkeypatch, formulation
):
    monkeypatch.setenv("OHQ_BASEFLOW_METHOD", "linear_reservoir")
    monkeypatch.setenv("OHQ_BASEFLOW_RECESSION_RATE_PER_DAY", "0.025")
    monkeypatch.setenv("OHQ_BASEFLOW_MIN_MOISTURE_CONTENT", "0.2")
    ws = Watershed(
        name="LinearBaseflow",
        subbasins=[
            Subbasin(
                id=1,
                name="Subbasin_1",
                area_km2=1.0,
                centroid_x=100.0,
                centroid_y=200.0,
            )
        ],
        reaches=[Reach(id=1, name="Reach_1", x_act=200.0, y_act=200.0)],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter(formulation=formulation).render(ws)
    baseflow_lines = [
        line
        for line in text.splitlines()
        if "name=Subbasin_1 to Reach_1 baseflow" in line
    ]

    assert len(baseflow_lines) == 1
    assert "type=Linear_baseflow" in baseflow_lines[0]
    assert "recession_rate=0.025[1/day]" in baseflow_lines[0]
    assert "min_moisture_content=0.2" in baseflow_lines[0]
    assert "length=" not in baseflow_lines[0]
    assert "area=" not in baseflow_lines[0]
    assert "type=groundwater_to_stream" not in text


@pytest.mark.parametrize(
    ("variable", "value", "message"),
    [
        ("OHQ_BASEFLOW_METHOD", "both", "must be 'darcy' or 'linear_reservoir'"),
        (
            "OHQ_BASEFLOW_RECESSION_RATE_PER_DAY",
            "0",
            "must be a finite positive number",
        ),
        (
            "OHQ_BASEFLOW_MIN_MOISTURE_CONTENT",
            "1.1",
            "must be between 0 and 1",
        ),
    ],
)
def test_linear_reservoir_baseflow_rejects_unsafe_settings(
    monkeypatch, variable, value, message
):
    monkeypatch.setenv("OHQ_BASEFLOW_METHOD", "linear_reservoir")
    monkeypatch.setenv(variable, value)

    with pytest.raises(ValueError, match=message):
        OHQWriter(formulation="standard_hru").render(Watershed(name="BadBaseflow"))


def test_temperature_forcing_adds_mass_conserving_snowpacks(monkeypatch):
    monkeypatch.setenv("OHQ_RAINFALL_FILE", "/data/precipitation.txt")
    monkeypatch.setenv("OHQ_TEMPERATURE_FILE", "/data/temperature.txt")
    ws = Watershed(
        name="SnowMixed",
        subbasins=[Subbasin(id=1, name="Subbasin_1", area_km2=1.0,
                            impervious_fraction=0.25,
                            centroid_x=100.0, centroid_y=200.0)],
        reaches=[Reach(id=1, name="Reach_1", x_act=200.0, y_act=200.0)],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter(formulation="mixed_hru").render(ws)

    assert "snowmelt.json" in text
    assert "type=Liquid_Precipitation,name=LiquidRain_Subbasin_1" in text
    assert "type=Snowfall,name=Snowfall_Subbasin_1" in text
    assert "type=Air_Temperature,name=AirTemperature" in text
    assert "Precipitation=LiquidRain_Subbasin_1" in text
    assert "Snowfall=Snowfall_Subbasin_1" in text
    assert "temperature_offset=0" in text
    assert "name=Snowpack_Subbasin_1_Pervious,area=750000[m~^2]" in text
    assert "name=Snowpack_Subbasin_1_Impervious,area=250000[m~^2]" in text
    assert "type=Pervious_Snowmelt_link" in text
    assert "type=Impervious_Snowmelt_link" in text


def test_temperature_forcing_connects_standard_hru_snowpack(monkeypatch):
    monkeypatch.setenv("OHQ_RAINFALL_FILE", "/data/precipitation.txt")
    monkeypatch.setenv("OHQ_TEMPERATURE_FILE", "/data/temperature.txt")
    ws = Watershed(
        name="SnowSingleSurface",
        subbasins=[Subbasin(id=1, name="Subbasin_1", area_km2=1.0,
                            centroid_x=100.0, centroid_y=200.0)],
        reaches=[Reach(id=1, name="Reach_1", x_act=200.0, y_act=200.0)],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter(formulation="standard_hru").render(ws)

    assert "name=Snowpack_Subbasin_1,area=1000000[m~^2]" in text
    assert "type=Snowmelt_link,name=Snowpack_Subbasin_1 melt" in text
    assert "type=Pervious_Snowmelt_link" not in text
    assert "type=Impervious_Snowmelt_link" not in text


def test_temperature_forcing_rejects_legacy_cn_catchment(monkeypatch):
    monkeypatch.setenv("OHQ_RAINFALL_FILE", "/data/precipitation.txt")
    monkeypatch.setenv("OHQ_TEMPERATURE_FILE", "/data/temperature.txt")
    ws = Watershed(
        name="SnowLegacy",
        subbasins=[Subbasin(id=1, name="Subbasin_1", area_km2=1.0)],
        outlet=Outlet(x_act=0.0, y_act=0.0),
        topology=[TopologyLink(1, "subbasin", "Subbasin_1", "sink", None,
                               "Outlet")],
    )

    with pytest.raises(ValueError, match="bypasses curve-number abstraction"):
        OHQWriter(formulation="legacy").render(ws)


def test_temperature_forcing_applies_subbasin_elevation_offsets(monkeypatch):
    monkeypatch.setenv("OHQ_RAINFALL_FILE", "/data/precipitation.txt")
    monkeypatch.setenv("OHQ_TEMPERATURE_FILE", "/data/temperature.txt")
    monkeypatch.setenv("OHQ_TEMPERATURE_REFERENCE_ELEVATION_M", "1500")
    monkeypatch.setenv("OHQ_TEMPERATURE_LAPSE_RATE_C_PER_KM", "-6.5")
    ws = Watershed(
        name="SnowElevations",
        subbasins=[
            Subbasin(id=1, name="Low", area_km2=1.0,
                     surface_elevation_m=1000.0, centroid_x=0.0, centroid_y=0.0),
            Subbasin(id=2, name="High", area_km2=1.0,
                     surface_elevation_m=2000.0, centroid_x=1.0, centroid_y=0.0),
        ],
        outlet=Outlet(x_act=2.0, y_act=0.0),
        topology=[
            TopologyLink(1, "subbasin", "Low", "sink", None, "Outlet"),
            TopologyLink(2, "subbasin", "High", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter(formulation="standard_hru").render(ws)

    assert "name=LiquidRain_Low,timeseries=/data/precipitation.txt,Temperature=/data/temperature.txt,temperature_offset=3.25" in text
    assert "name=Snowfall_Low,timeseries=/data/precipitation.txt,Temperature=/data/temperature.txt,temperature_offset=3.25" in text
    assert "name=LiquidRain_High,timeseries=/data/precipitation.txt,Temperature=/data/temperature.txt,temperature_offset=-3.25" in text
    assert "name=Snowfall_High,timeseries=/data/precipitation.txt,Temperature=/data/temperature.txt,temperature_offset=-3.25" in text
    assert "name=Snowpack_Low,area=1000000[m~^2],Snowfall=Snowfall_Low,Temperature=AirTemperature,temperature_offset=3.25" in text
    assert "name=Snowpack_High,area=1000000[m~^2],Snowfall=Snowfall_High,Temperature=AirTemperature,temperature_offset=-3.25" in text


@pytest.mark.parametrize(
    ("variable", "value"),
    [
        ("OHQ_TEMPERATURE_REFERENCE_ELEVATION_M", "bad"),
        ("OHQ_TEMPERATURE_REFERENCE_ELEVATION_M", "nan"),
        ("OHQ_TEMPERATURE_LAPSE_RATE_C_PER_KM", "inf"),
    ],
)
def test_temperature_adjustment_rejects_nonfinite_settings(
    monkeypatch, variable, value
):
    monkeypatch.setenv("OHQ_TEMPERATURE_FILE", "/data/temperature.txt")
    monkeypatch.setenv("OHQ_TEMPERATURE_REFERENCE_ELEVATION_M", "100")
    monkeypatch.setenv(variable, value)
    with pytest.raises(ValueError, match="must be a finite number"):
        OHQWriter(formulation="standard_hru").render(Watershed(name="BadSnow"))


def test_temperature_lapse_rate_requires_reference_elevation(monkeypatch):
    monkeypatch.setenv("OHQ_TEMPERATURE_FILE", "/data/temperature.txt")
    monkeypatch.delenv("OHQ_TEMPERATURE_REFERENCE_ELEVATION_M", raising=False)
    monkeypatch.setenv("OHQ_TEMPERATURE_LAPSE_RATE_C_PER_KM", "-6.5")
    with pytest.raises(ValueError, match="requires"):
        OHQWriter(formulation="standard_hru").render(Watershed(name="BadSnow"))


def test_temperature_reference_requires_subbasin_elevation(monkeypatch):
    monkeypatch.setenv("OHQ_TEMPERATURE_FILE", "/data/temperature.txt")
    monkeypatch.setenv("OHQ_TEMPERATURE_REFERENCE_ELEVATION_M", "100")
    ws = Watershed(
        name="MissingElevation",
        subbasins=[Subbasin(id=1, name="Subbasin_1", area_km2=1.0,
                            centroid_x=0.0, centroid_y=0.0)],
        outlet=Outlet(x_act=1.0, y_act=0.0),
        topology=[TopologyLink(1, "subbasin", "Subbasin_1", "sink", None,
                               "Outlet")],
    )

    with pytest.raises(ValueError, match="no finite subbasin elevation"):
        OHQWriter(formulation="standard_hru").render(ws)


def test_temperature_forcing_is_opt_in(monkeypatch):
    monkeypatch.delenv("OHQ_TEMPERATURE_FILE", raising=False)
    ws = Watershed(
        name="RainOnly",
        subbasins=[Subbasin(id=1, name="Subbasin_1", area_km2=1.0,
                            centroid_x=100.0, centroid_y=200.0)],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[TopologyLink(1, "subbasin", "Subbasin_1", "sink", None,
                               "Outlet")],
    )

    text = OHQWriter(formulation="legacy").render(ws)

    assert "create source;type=Precipitation,name=Rain" in text
    assert "snowmelt.json" not in text
    assert "Snowpack" not in text


def test_et_is_opt_in_and_connects_both_hru_types(monkeypatch):
    ws = Watershed(
        name="ETCheck",
        subbasins=[Subbasin(id=1, name="Subbasin_1", area_km2=1.0,
                            centroid_x=100.0, centroid_y=200.0)],
        reaches=[Reach(id=1, name="Reach_1", x_act=200.0, y_act=200.0)],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )
    monkeypatch.delenv("OHQ_ET_FILE", raising=False)
    assert "Evapotranspiration=ET" not in OHQWriter(formulation="mixed_hru").render(ws)
    monkeypatch.setenv("OHQ_ET_FILE", "/data/et_m_per_day.csv")
    for formulation, composite in (
        ("mixed_hru", "Mixed_Hydrologic_Response_Unit"),
        ("standard_hru", "Hydrologic_Response_Unit"),
    ):
        text = OHQWriter(formulation=formulation).render(ws)
        assert "soil_evapotranspiration_models.json" in text
        assert "create source;type=Evapotranspiration_Time_Series (Soil),name=ET,ET_timeseries=/data/et_m_per_day.csv" in text
        assert f"create composite;type={composite},name=Subbasin_1," in text
        assert "Evapotranspiration=ET" in text
        assert "timeseries=/data/et_m_per_day.csv" not in text.replace("ET_timeseries=", "")
    standard = OHQWriter(formulation="standard_hru").render(ws)
    assert "type=Catchment_link,name=Subbasin_1 to Reach_1 surface" in standard
    assert "type=groundwater_to_stream,name=Subbasin_1 to Reach_1 baseflow" in standard
    legacy = OHQWriter(formulation="legacy").render(ws)
    assert "Evapotranspiration=ET" not in legacy


def test_et_file_path_cannot_change_ohq_commands():
    with pytest.raises(ValueError, match="delimiter"):
        et_lines("et.csv;create block")


def test_writer_renders_mixed_hru_soil_texture_as_van_genuchten_parameters():
    ws = Watershed(
        name="MixedSoil",
        subbasins=[
            Subbasin(
                id=1,
                name="Subbasin_1",
                area_km2=1.0,
                impervious_fraction=0.27,
                surface_elevation_m=84.2,
                centroid_x=100.0,
                centroid_y=200.0,
                sand_pct=20.0,
                clay_pct=15.0,
            )
        ],
        reaches=[Reach(id=1, name="Reach_1", x_act=200.0, y_act=200.0)],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter(formulation="mixed_hru").render(ws)

    # sand=20%, clay=15% (silt=65%) classifies as silt loam; parameters are
    # the Carsel & Parrish (1988) averages for that class.
    assert "K_sat=0.108[m/day]" in text
    assert "alpha_vG=2[1/m]" in text
    assert "n_vG=1.41" in text
    assert "theta_sat=0.45" in text
    assert "theta_res=0.067" in text


def test_writer_parameterizes_reach_as_trapezoidal_channel_connected_to_catchment():
    ws = Watershed(
        name="Parameterized",
        subbasins=[
            Subbasin(
                id=1,
                name="Subbasin_1",
                area_km2=0.5,
                curve_number=72,
                downstream="Reach_1",
                centroid_x=100.0,
                centroid_y=200.0,
            )
        ],
        reaches=[
            Reach(
                id=1,
                name="Reach_1",
                length_m=432.1,
                base_width_m=3.5,
                side_slope_z=1.75,
                manning_n=0.041,
                z_up_m=101.2,
                z_dn_m=98.6,
                downstream="Outlet",
                x_act=200.0,
                y_act=200.0,
                x_up_act=150.0,
                y_up_act=200.0,
                x_dn_act=250.0,
                y_dn_act=200.0,
            )
        ],
        outlet=Outlet(name="Outlet", x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter().render(ws)

    assert "create block;type=Trapezoidal Channel Segment,name=Reach_1" in text
    assert "base_width=3.5[m]" in text
    assert "side_slope=1.75" in text
    assert "ManningCoeff=0.041" in text
    assert "bottom_elevation=98.6[m]" in text
    assert "length=432.1[m]" in text
    # CN_Catchment exposes its outflow through CN_outlet (from its internal
    # final cascade reservoir), not the plain-Catchment Catchment_link.
    assert "create link;from=Subbasin_1,to=Reach_1,type=CN_outlet" in text


def test_written_formulations_have_distinct_simulation_outputs(tmp_path):
    ws = Watershed(name="SameSite", outlet=Outlet(x_act=0.0, y_act=0.0))
    for formulation in ("legacy", "mixed_hru", "standard_hru"):
        path = tmp_path / f"site_{formulation}.ohq"
        OHQWriter(formulation=formulation).write(ws, path)
        text = path.read_text()
        assert f"quantity=alloutputfile, value={path.stem}_OHQ_output.txt" in text
        assert f"quantity=observed_outputfile, value={path.stem}_observed.txt" in text
        assert "quantity=outputfile," not in text
