import pytest

from ohqbuilder.model.outlet import Outlet
from ohqbuilder.model.reach import Reach
from ohqbuilder.model.watershed import Watershed
from ohqbuilder.model.subbasin import Subbasin
from ohqbuilder.model.topology import TopologyLink
from ohqbuilder.writers.ohq_writer import OHQWriter
from ohqbuilder.writers.rainfall_writer import rainfall_lines


def test_writer_renders_subbasin():
    ws = Watershed(
        name="Test",
        subbasins=[
            Subbasin(
                id=1,
                name="Subbasin_1",
                area_km2=1.0,
                curve_number=75,
                downstream="Outlet",
                centroid_x=100.0,
                centroid_y=200.0,
            )
        ],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[TopologyLink(1, "subbasin", "Subbasin_1", "sink", None, "Outlet")],
    )
    txt = OHQWriter().render(ws)
    # CN_Catchment is a composite type: it must be created with "create
    # composite" (which instantiates its internal Retention/R1-R5 cascade),
    # not "create block" (which would leave it an empty, non-functional shell).
    assert "create composite;type=CN_Catchment,name=Subbasin_1" in txt
    assert "CN=75" in txt
    assert "create block;type=fixed_head,name=Outlet" in txt


def test_writer_can_omit_comments():
    ws = Watershed(name="NoComments", outlet=Outlet(x_act=0.0, y_act=0.0))

    txt = OHQWriter(include_comments=False).render(ws)

    assert "# Generated by GIStoOHQ" not in txt
    assert "outputfile, value=NoComments_OHQ_output.txt" in txt
    assert "create block;type=fixed_head,name=Outlet" in txt


def test_simulation_window_rejects_reversed_or_invalid_times(monkeypatch):
    ws = Watershed(name="BadWindow", outlet=Outlet(x_act=0.0, y_act=0.0))

    monkeypatch.setenv("OHQ_SIM_START_TIME", "5")
    monkeypatch.setenv("OHQ_SIM_END_TIME", "5")
    with pytest.raises(ValueError, match="greater than"):
        OHQWriter().render(ws)

    monkeypatch.setenv("OHQ_SIM_START_TIME", "5")
    monkeypatch.setenv("OHQ_SIM_END_TIME", "1")
    with pytest.raises(ValueError, match="greater than"):
        OHQWriter().render(ws)

    monkeypatch.setenv("OHQ_SIM_START_TIME", "not-a-number")
    monkeypatch.setenv("OHQ_SIM_END_TIME", "1")
    with pytest.raises(ValueError, match="must be numbers"):
        OHQWriter().render(ws)

    monkeypatch.setenv("OHQ_SIM_START_TIME", "0")
    monkeypatch.setenv("OHQ_SIM_END_TIME", "inf")
    with pytest.raises(ValueError, match="must be finite"):
        OHQWriter().render(ws)


def test_rainfall_source_does_not_reference_an_invented_file(monkeypatch):
    monkeypatch.delenv("OHQ_RAINFALL_FILE", raising=False)

    assert rainfall_lines(Watershed(name="NoRainfallFile")) == [
        "create source;type=Precipitation,name=Rain"
    ]


def test_rainfall_source_uses_explicitly_configured_file(monkeypatch):
    monkeypatch.setenv("OHQ_RAINFALL_FILE", "/data/valid_rainfall.txt")

    assert rainfall_lines(Watershed(name="Configured")) == [
        "create source;type=Precipitation,name=Rain,"
        "timeseries=/data/valid_rainfall.txt"
    ]


def test_writer_renders_mixed_hru_with_area_fraction_and_three_outflows():
    ws = Watershed(
        name="Mixed",
        subbasins=[
            Subbasin(
                id=1,
                name="Subbasin_1",
                area_km2=1.0,
                impervious_fraction=0.27,
                surface_elevation_m=84.2,
                centroid_x=100.0,
                centroid_y=200.0,
            )
        ],
        reaches=[Reach(id=1, name="Reach_1", x_act=200.0, y_act=200.0)],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter(formulation="mixed_hru").render(ws)

    assert "mixed_hydrologic_response_unit.json" in text
    assert "mixed_hydrologic_response_unit_final_v2.json" not in text
    # Composite types must use "create composite" - only that command path
    # instantiates a composite's internal members (Soil_1-3, Groundwater,
    # Impervious_Catchment, ...) and propagates its applyto-derived formulas.
    # "create block" builds an empty shell with no internal members at all.
    assert "create composite;type=Mixed_Hydrologic_Response_Unit,name=Subbasin_1" in text
    assert "create block;type=Mixed_Hydrologic_Response_Unit" not in text
    assert "impervious_fraction=0.27" in text
    assert "surface_elevation=84.2[m]" in text
    assert "Runoff_coeff=" not in text
    # Mixed_Hydrologic_Response_Unit's Reach/Impervious_Reach members can only
    # be resolved as external exits through their own distinct connector
    # types (Reach_link/Impervious_Reach_link); a composite can resolve just
    # one exit per link "type" string, so both cannot share the underlying
    # Trapezoidal_Channel_link type. Confirmed by actually solving a
    # generated .ohq through OpenHydroQual-Console: using
    # Trapezoidal_Channel_link here fails with "cannot start at composite".
    assert "from=Subbasin_1,to=Reach_1,type=Reach_link" in text
    assert "from=Subbasin_1,to=Reach_1,type=Impervious_Reach_link" in text
    assert "type=Trapezoidal_Channel_link" not in text
    assert "from=Subbasin_1,to=Reach_1,type=groundwater_to_stream" in text
    # groundwater_to_stream's length/area have no template default and a
    # strict >0 criteria (see groundwater.json); an unparameterized link
    # fails model verification before solving, confirmed by actually running
    # a generated .ohq through OpenHydroQual-Console.
    #
    # Flow-path length is now sized from relief/TARGET_GRADIENT (2%), not a
    # bare constant (see ohq_writer.py's Groundwater-fixes commit). This
    # fixture's Reach_1 has no elevation set, and reach_bottom_elevation()
    # falls back to 0 for that - a real, currently-unaddressed gap (missing
    # elevation data reads as "reach is at sea level", not "unknown"), which
    # here manufactures relief = |84.2 - 0| = 84.2m and thus length =
    # 84.2/0.02 = 4210m for this small, low-relief-in-reality test subbasin.
    # This assertion tracks that actual (if imperfect) behavior; it is not an
    # endorsement of treating missing elevation as 0.
    assert "type=groundwater_to_stream,name=Subbasin_1 to Reach_1 baseflow,length=4210[m]" in text
    # No SSURGO texture data on this Subbasin: soil parameters must be
    # omitted so mixed_hydrologic_response_unit.json's generic template
    # defaults apply, not silently written as some fabricated value.
    assert "K_sat=" not in text
    assert "alpha_vG=" not in text
    assert "n_vG=" not in text
    assert "theta_sat=" not in text
    assert "theta_res=" not in text


def test_writer_renders_mixed_hru_soil_texture_as_van_genuchten_parameters():
    ws = Watershed(
        name="MixedSoil",
        subbasins=[
            Subbasin(
                id=1,
                name="Subbasin_1",
                area_km2=1.0,
                impervious_fraction=0.27,
                surface_elevation_m=84.2,
                centroid_x=100.0,
                centroid_y=200.0,
                sand_pct=20.0,
                clay_pct=15.0,
            )
        ],
        reaches=[Reach(id=1, name="Reach_1", x_act=200.0, y_act=200.0)],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter(formulation="mixed_hru").render(ws)

    # sand=20%, clay=15% (silt=65%) classifies as silt loam; parameters are
    # the Carsel & Parrish (1988) averages for that class.
    assert "K_sat=0.108[m/day]" in text
    assert "alpha_vG=2[1/m]" in text
    assert "n_vG=1.41" in text
    assert "theta_sat=0.45" in text
    assert "theta_res=0.067" in text


def test_writer_parameterizes_reach_as_trapezoidal_channel_connected_to_catchment():
    ws = Watershed(
        name="Parameterized",
        subbasins=[
            Subbasin(
                id=1,
                name="Subbasin_1",
                area_km2=0.5,
                curve_number=72,
                downstream="Reach_1",
                centroid_x=100.0,
                centroid_y=200.0,
            )
        ],
        reaches=[
            Reach(
                id=1,
                name="Reach_1",
                length_m=432.1,
                base_width_m=3.5,
                side_slope_z=1.75,
                manning_n=0.041,
                z_up_m=101.2,
                z_dn_m=98.6,
                downstream="Outlet",
                x_act=200.0,
                y_act=200.0,
                x_up_act=150.0,
                y_up_act=200.0,
                x_dn_act=250.0,
                y_dn_act=200.0,
            )
        ],
        outlet=Outlet(name="Outlet", x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter().render(ws)

    assert "create block;type=Trapezoidal Channel Segment,name=Reach_1" in text
    assert "base_width=3.5[m]" in text
    assert "side_slope=1.75" in text
    assert "ManningCoeff=0.041" in text
    assert "bottom_elevation=98.6[m]" in text
    assert "length=432.1[m]" in text
    # CN_Catchment exposes its outflow through CN_outlet (from its internal
    # final cascade reservoir), not the plain-Catchment Catchment_link.
    assert "create link;from=Subbasin_1,to=Reach_1,type=CN_outlet" in text
