from ohqbuilder.model.outlet import Outlet
from ohqbuilder.model.reach import Reach
from ohqbuilder.model.watershed import Watershed
from ohqbuilder.model.subbasin import Subbasin
from ohqbuilder.model.topology import TopologyLink
from ohqbuilder.writers.ohq_writer import OHQWriter
from ohqbuilder.writers.rainfall_writer import rainfall_lines


def test_writer_renders_subbasin():
    ws = Watershed(
        name="Test",
        subbasins=[
            Subbasin(
                id=1,
                name="Subbasin_1",
                area_km2=1.0,
                curve_number=75,
                downstream="Outlet",
                centroid_x=100.0,
                centroid_y=200.0,
            )
        ],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[TopologyLink(1, "subbasin", "Subbasin_1", "sink", None, "Outlet")],
    )
    txt = OHQWriter().render(ws)
    assert "create block;type=Catchment,name=Subbasin_1" in txt
    assert "create block;type=fixed_head,name=Outlet" in txt


def test_writer_can_omit_comments():
    ws = Watershed(name="NoComments", outlet=Outlet(x_act=0.0, y_act=0.0))

    txt = OHQWriter(include_comments=False).render(ws)

    assert "# Generated by GIStoOHQ" not in txt
    assert "outputfile, value=NoComments_OHQ_output.txt" in txt
    assert "create block;type=fixed_head,name=Outlet" in txt


def test_rainfall_source_does_not_reference_an_invented_file(monkeypatch):
    monkeypatch.delenv("OHQ_RAINFALL_FILE", raising=False)

    assert rainfall_lines(Watershed(name="NoRainfallFile")) == [
        "create source;type=Precipitation,name=Rain"
    ]


def test_rainfall_source_uses_explicitly_configured_file(monkeypatch):
    monkeypatch.setenv("OHQ_RAINFALL_FILE", "/data/valid_rainfall.txt")

    assert rainfall_lines(Watershed(name="Configured")) == [
        "create source;type=Precipitation,name=Rain,"
        "timeseries=/data/valid_rainfall.txt"
    ]


def test_writer_renders_mixed_hru_with_area_fraction_and_three_outflows():
    ws = Watershed(
        name="Mixed",
        subbasins=[
            Subbasin(
                id=1,
                name="Subbasin_1",
                area_km2=1.0,
                impervious_fraction=0.27,
                centroid_x=100.0,
                centroid_y=200.0,
            )
        ],
        reaches=[Reach(id=1, name="Reach_1", x_act=200.0, y_act=200.0)],
        outlet=Outlet(x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter(formulation="mixed_hru").render(ws)

    assert "mixed_hydrologic_response_unit.json" in text
    assert "mixed_hydrologic_response_unit_final_v2.json" not in text
    assert "type=Mixed_Hydrologic_Response_Unit,name=Subbasin_1" in text
    assert "impervious_fraction=0.27" in text
    assert "Runoff_coeff=" not in text
    assert text.count(
        "from=Subbasin_1,to=Reach_1,type=Trapezoidal_Channel_link"
    ) == 2
    assert "from=Subbasin_1,to=Reach_1,type=groundwater_to_stream" in text


def test_writer_parameterizes_reach_as_trapezoidal_channel_connected_to_catchment():
    ws = Watershed(
        name="Parameterized",
        subbasins=[
            Subbasin(
                id=1,
                name="Subbasin_1",
                area_km2=0.5,
                curve_number=72,
                downstream="Reach_1",
                centroid_x=100.0,
                centroid_y=200.0,
            )
        ],
        reaches=[
            Reach(
                id=1,
                name="Reach_1",
                length_m=432.1,
                base_width_m=3.5,
                side_slope_z=1.75,
                manning_n=0.041,
                z_up_m=101.2,
                z_dn_m=98.6,
                downstream="Outlet",
                x_act=200.0,
                y_act=200.0,
                x_up_act=150.0,
                y_up_act=200.0,
                x_dn_act=250.0,
                y_dn_act=200.0,
            )
        ],
        outlet=Outlet(name="Outlet", x_act=300.0, y_act=200.0),
        topology=[
            TopologyLink(1, "subbasin", "Subbasin_1", "reach", 1, "Reach_1"),
            TopologyLink(1, "reach", "Reach_1", "sink", None, "Outlet"),
        ],
    )

    text = OHQWriter().render(ws)

    assert "create block;type=Trapezoidal Channel Segment,name=Reach_1" in text
    assert "base_width=3.5[m]" in text
    assert "side_slope=1.75" in text
    assert "ManningCoeff=0.041" in text
    assert "bottom_elevation=98.6[m]" in text
    assert "length=432.1[m]" in text
    assert "create link;from=Subbasin_1,to=Reach_1,type=Catchment_link" in text
