from __future__ import annotations
from pathlib import Path
from ..model.watershed import Watershed
from .routing_writer import routing_lines
from .rainfall_writer import rainfall_lines
from .block_writer import BlockWriter

class OHQWriter:
    """Write a first-pass OpenHydroQual-style OHQ model.

    The writer is isolated so the exact OpenHydroQual parser grammar can be
    refined later without changing readers, validators, or topology handling.
    """

    def __init__(self, include_comments: bool = True):
        self.include_comments = include_comments

    def write(self, watershed: Watershed, path: Path) -> None:
        path.write_text(self.render(watershed), encoding="utf-8")

    def render(self, watershed: Watershed) -> str:
        w = BlockWriter()
        if self.include_comments:
            w.comment("Generated by OpenHydroQual-GIS")
            w.comment("Topology is read from topology.gpkg; this writer does not infer connectivity.")
        w.line(f"Project: {watershed.name}")
        w.line()

        if self.include_comments:
            w.comment("Meteorological inputs")
        for line in rainfall_lines(watershed):
            w.line(line)
        w.line()

        if self.include_comments:
            w.comment("Subbasin runoff generation blocks")
        for s in watershed.subbasins:
            w.block(f"Subbasin: {s.name}", [
                "Type: CN_Catchment",
                f"Area_km2: {s.area_km2 if s.area_km2 is not None else ''}",
                f"CurveNumber: {s.curve_number if s.curve_number is not None else ''}",
                f"Slope_pct: {s.slope_pct if s.slope_pct is not None else ''}",
                f"Tc_min: {s.tc_min if s.tc_min is not None else ''}",
                f"Lag_min: {s.lag_min if s.lag_min is not None else ''}",
                f"Downstream: {s.downstream or ''}",
            ])

        if self.include_comments:
            w.comment("Reach routing blocks")
        for r in watershed.reaches:
            w.block(f"Reach: {r.name}", routing_lines(r))

        if self.include_comments:
            w.comment("Junction/mixer blocks")
        for j in watershed.junctions:
            w.block(f"Junction: {j.name}", [
                "Type: Junction",
                f"X: {j.x if j.x is not None else ''}",
                f"Y: {j.y if j.y is not None else ''}",
                f"Downstream: {j.downstream or ''}",
            ])

        w.block(f"Outlet: {watershed.outlet.name}", ["Type: Outlet"])

        if self.include_comments:
            w.comment("Explicit topology table")
        for link in watershed.topology:
            w.line(f"Connect: {link.name} -> {link.ds_name or ''}")
        return w.text()
