from __future__ import annotations

import math
import os
from pathlib import Path
from typing import Any, Iterable

from ..model.watershed import Watershed
from .block_writer import BlockWriter
from .rainfall_writer import rainfall_lines
from .routing_writer import routing_lines, sewer_pipe_properties


def _safe_name(value: Any, fallback: str) -> str:
    text = str(value or fallback)
    text = text.replace(";", "_").replace(",", "_")
    text = " ".join(text.split())
    return text or fallback


def _finite(value: Any, default: float = 0.0) -> float:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return default
    return number if math.isfinite(number) else default


def _positive(value: Any, default: float) -> float:
    number = _finite(value, default)
    return number if number > 0.0 else default


def _resource_path(filename: str) -> str:
    """Resolve an OpenHydroQual resource path without hard-coding a machine.

    Export ``OPENHYDROQUAL_RESOURCES`` to the local OpenHydroQual resources
    directory.  The default matches the Linux layout used by this project.
    """

    root = os.environ.get(
        "OPENHYDROQUAL_RESOURCES",
        "/mnt/3rd900/Projects/OpenHydroQual/resources",
    )
    return str(Path(root) / filename)


def _ordered_unique(items: Iterable[str]) -> list[str]:
    result: list[str] = []
    seen: set[str] = set()
    for item in items:
        if item and item not in seen:
            result.append(item)
            seen.add(item)
    return result


class OHQWriter:
    """Write a native OpenHydroQual command-script model.

    This writer follows the grammar used by working OpenHydroQual ``.ohq``
    files: ``loadtemplate``, ``addtemplate``, ``create source``,
    ``create block``, ``create link``, and ``setvalue``.

    Current watershed representation
    --------------------------------
    * GIS subbasins -> OpenHydroQual ``Catchment`` blocks.
    * GIS reaches   -> small ``Catch basin`` routing blocks.
    * GIS junctions -> ``Catch basin`` routing blocks.
    * Watershed outlet -> ``fixed_head`` block.
    * Catchment runoff links -> ``Catchment_link``.
    * Reach/junction routing links -> ``Sewer_pipe``.

    The reach-as-routing-node mapping is intentionally conservative.  It is a
    valid OHQ component mapping, but it is not a claim that a sewer pipe is the
    final calibrated representation of a natural stream.  Channel-specific
    plug-ins can replace this mapping later without changing GIS ingestion.
    """

    def __init__(self, include_comments: bool = True):
        self.include_comments = include_comments

    def write(self, watershed: Watershed, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(self.render(watershed), encoding="utf-8")

    def render(self, watershed: Watershed) -> str:
        writer = BlockWriter()

        model_name = _safe_name(getattr(watershed, "name", None), "Watershed")
        outlet_obj = getattr(watershed, "outlet", None)
        outlet_name = _safe_name(
            getattr(outlet_obj, "name", None),
            f"{model_name} Outlet",
        )

        subbasins = list(getattr(watershed, "subbasins", []) or [])
        reaches = list(getattr(watershed, "reaches", []) or [])
        junctions = list(getattr(watershed, "junctions", []) or [])
        topology = list(getattr(watershed, "topology", []) or [])

        subbasin_names = {
            _safe_name(getattr(item, "name", None), f"Subbasin {index + 1}")
            for index, item in enumerate(subbasins)
        }
        reach_by_name = {
            _safe_name(getattr(item, "name", None), f"Reach {index + 1}"): item
            for index, item in enumerate(reaches)
        }
        junction_names = {
            _safe_name(getattr(item, "name", None), f"Junction {index + 1}")
            for index, item in enumerate(junctions)
        }

        all_object_names = set(subbasin_names)
        all_object_names.update(reach_by_name)
        all_object_names.update(junction_names)
        all_object_names.add(outlet_name)

        if self.include_comments:
            writer.comment("Generated by GIStoOHQ using native OpenHydroQual grammar")
            writer.comment(
                "GIS reaches are represented as Catch basin routing nodes connected "
                "with Sewer_pipe links."
            )
            writer.comment(
                "Set OPENHYDROQUAL_RESOURCES and OHQ_RAINFALL_FILE when local paths "
                "differ from the defaults."
            )

        writer.loadtemplate(_resource_path("main_components.json"))
        writer.addtemplate(_resource_path("rainfall_runoff.json"))
        writer.addtemplate(_resource_path("Sewer_system.json"))
        writer.line()

        if self.include_comments:
            writer.comment("Meteorological source")
        for line in rainfall_lines(watershed):
            writer.line(line)
        writer.line()

        # Place blocks in readable columns in the OHQ GUI.
        sub_x = -700
        reach_x = -150
        junction_x = 400
        outlet_x = 900
        vertical_spacing = 190

        if self.include_comments:
            writer.comment("Catchment runoff-generation blocks")

        for index, subbasin in enumerate(subbasins):
            name = _safe_name(
                getattr(subbasin, "name", None),
                f"Subbasin {index + 1}",
            )
            area_km2 = _positive(getattr(subbasin, "area_km2", None), 1.0e-6)
            area_m2 = area_km2 * 1_000_000.0

            slope_pct = _finite(getattr(subbasin, "slope_pct", None), 1.0)
            slope = max(slope_pct / 100.0, 1.0e-6)

            curve_number = _finite(
                getattr(subbasin, "curve_number", None),
                75.0,
            )
            # OpenHydroQual's standard Catchment block uses Runoff_coeff rather
            # than SCS Curve Number.  This bounded mapping is an explicit first
            # approximation and should be calibrated or replaced as needed.
            runoff_coeff = min(max(curve_number / 100.0, 0.01), 1.0)

            width = max(math.sqrt(area_m2), 1.0)
            elevation = _finite(
                getattr(subbasin, "elevation_m", None),
                _finite(getattr(subbasin, "mean_elevation_m", None), 0.0),
            )

            writer.create_block(
                "Catchment",
                name=name,
                properties=[
                    ("area", f"{area_m2:.12g}[m~^2]"),
                    ("Slope", f"{slope:.12g}"),
                    ("Width", f"{width:.12g}[m]"),
                    ("ManningCoeff", "0.15"),
                    ("Runoff_coeff", f"{runoff_coeff:.12g}"),
                    ("Precipitation", "Rain"),
                    ("Evapotranspiration", ""),
                    ("inflow", ""),
                    ("depth", "0[m]"),
                    ("elevation", f"{elevation:.12g}[m]"),
                    ("depression_storage", "0.005[m]"),
                    ("loss_coefficient", "0[1/day]"),
                    ("x", sub_x),
                    ("y", index * vertical_spacing),
                    ("_width", 180),
                    ("_height", 120),
                ],
            )

        if self.include_comments:
            writer.comment("Reach routing nodes")

        for index, (name, reach) in enumerate(reach_by_name.items()):
            properties: list[tuple[str, Any]] = []
            for item in routing_lines(reach):
                if "=" in item:
                    key, value = item.split("=", 1)
                    if key != "type":
                        properties.append((key, value))
            properties.extend(
                [
                    ("x", reach_x),
                    ("y", index * vertical_spacing),
                    ("_width", 180),
                    ("_height", 120),
                ]
            )
            writer.create_block("Catch basin", name=name, properties=properties)

        if self.include_comments:
            writer.comment("Junction routing nodes")

        for index, junction in enumerate(junctions):
            name = _safe_name(
                getattr(junction, "name", None),
                f"Junction {index + 1}",
            )
            elevation = _finite(
                getattr(junction, "elevation_m", None),
                _finite(getattr(junction, "z_m", None), 0.0),
            )
            writer.create_block(
                "Catch basin",
                name=name,
                properties=[
                    ("area", "1[m~^2]"),
                    ("bottom_elevation", f"{elevation:.12g}[m]"),
                    ("inflow", ""),
                    ("x", junction_x),
                    ("y", index * vertical_spacing),
                    ("_width", 180),
                    ("_height", 120),
                ],
            )

        writer.create_block(
            "fixed_head",
            name=outlet_name,
            properties=[
                ("head", "0[m]"),
                ("Storage", "1000000000[m~^3]"),
                ("x", outlet_x),
                ("y", 0),
                ("_width", 180),
                ("_height", 120),
            ],
        )
        writer.line()

        if self.include_comments:
            writer.comment("Explicit topology links")

        emitted_pairs: set[tuple[str, str]] = set()
        terminal_candidates = set(all_object_names)
        terminal_candidates.discard(outlet_name)

        for index, link in enumerate(topology):
            source = _safe_name(
                getattr(link, "name", None),
                f"Topology source {index + 1}",
            )
            target_raw = getattr(link, "ds_name", None)
            target = _safe_name(target_raw, "") if target_raw else ""

            if not source or not target:
                if self.include_comments:
                    writer.comment(
                        f"Skipped topology row {index + 1}: blank source or downstream."
                    )
                continue
            if source == target:
                if self.include_comments:
                    writer.comment(
                        f"Skipped invalid self-link: {source} -> {target}"
                    )
                continue
            if source not in all_object_names or target not in all_object_names:
                if self.include_comments:
                    writer.comment(
                        f"Skipped unresolved topology link: {source} -> {target}"
                    )
                continue
            if (source, target) in emitted_pairs:
                continue

            emitted_pairs.add((source, target))
            terminal_candidates.discard(source)

            link_name = _safe_name(
                getattr(link, "link_name", None),
                f"{source} to {target}",
            )

            if source in subbasin_names:
                writer.create_link(
                    "Catchment_link",
                    name=link_name,
                    source=source,
                    target=target,
                )
            else:
                reach = reach_by_name.get(source)
                properties = (
                    sewer_pipe_properties(reach)
                    if reach is not None
                    else [
                        ("ManningCoeff", "0.035"),
                        ("diameter", "1[m]"),
                        ("length", "1[m]"),
                        ("start_elevation", "0.001[m]"),
                        ("end_elevation", "0[m]"),
                    ]
                )
                writer.create_link(
                    "Sewer_pipe",
                    name=link_name,
                    source=source,
                    target=target,
                    properties=properties,
                )

        # Attach unresolved terminal routing nodes to the outlet so the result
        # has a single sink.  Catchments are not force-connected here because a
        # missing catchment downstream assignment should remain visible.
        for source in _ordered_unique(
            name
            for name in terminal_candidates
            if name in reach_by_name or name in junction_names
        ):
            pair = (source, outlet_name)
            if pair in emitted_pairs or source == outlet_name:
                continue
            writer.create_link(
                "Sewer_pipe",
                name=f"{source} to {outlet_name}",
                source=source,
                target=outlet_name,
                properties=[
                    ("ManningCoeff", "0.035"),
                    ("diameter", "1[m]"),
                    ("length", "1[m]"),
                    ("start_elevation", "0.001[m]"),
                    ("end_elevation", "0[m]"),
                ],
            )
            emitted_pairs.add(pair)

        writer.line()
        writer.setvalue("system", "simulation_start_time", "0")
        writer.setvalue("system", "simulation_end_time", "1")
        writer.setvalue("system", "outputfile", f"{model_name}_OHQ_output.txt")

        return writer.text()
